### ISSUE TITLE
Thunderstruck download issue

### ISSUE THREAD

**Issue by kodiultimate** [MrBlamo420/Project#19]
Hi MrBlamo

Not sure who do I speak regarding thunderstruck project?

Please point me into right direction

appreciate

**Comment by MrBlamo420** [comment]
Downloads fine and they show up if you set the location.

**Comment by kodiultimate** [comment]
The issue is when I set location and convert it to special://
Used to work before but for some reason it doesn't in the latest version.
Converting it to special:// comes handy when I share my build with family and friends
Could you please have look at it please
here is part of the log

16:55:51.419 T:5488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: [Error 123] The file name, directory name or volume label syntax is incorrect: 'special:'
                                            Traceback (most recent call last):
                                              File "K:\Kodi 17 Main\portable_data\addons\plugin.audio.thunderstruck\default.py", line 1458, in <module>
                                                download_album(url, name, iconimage)
                                              File "K:\Kodi 17 Main\portable_data\addons\plugin.audio.thunderstruck\default.py", line 666, in download_album
                                                artist_path = create_directory(MUSIC_DIR, artist)
                                              File "K:\Kodi 17 Main\portable_data\addons\plugin.audio.thunderstruck\default.py", line 1169, in create_directory
                                                os.makedirs(dir_path)
                                              File "K:\Kodi 17 Main\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "K:\Kodi 17 Main\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "K:\Kodi 17 Main\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "K:\Kodi 17 Main\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "K:\Kodi 17 Main\system\python\Lib\os.py", line 157, in makedirs
                                                mkdir(name, mode)
                                            WindowsError: [Error 123] The file name, directory name or volume label syntax is incorrect: 'special:'
                                            -->End of Python script error report<--

**Comment by MrBlamo420** [comment]
No sorry downloads are for a person to download. You cannot conveet to
special

**Comment by MrBlamo420** [comment]
and it Hasn't got a update recently
